import type { Metadata } from "next";
import { myFont } from "./fonts";
import "./globals.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      {/*    <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
        <body className={myFont.className}>
        <div className="w-full h-screen flex flex-col justify-center items-center overflow-y-hidden">
          <Header />
          <main className="h-full w-full container mx-auto flex flex-col justify-center items-center overflow-y-auto">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
